name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
baseurl: /jekyll
url: http://programminghistorian.org
baseurl: /jekyll
permalink: :categories/:title
safe: true
pygments: true
markdown: redcarpet
redcarpet:
 extensions: ['tables', 'smart']
