name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
baseurl: /jekyll
url: http://programminghistorian.org
permalink: :categories/:title
exclude: [deprecated]
safe: true
pygments: true
markdown: redcarpet
redcarpet:
 extensions: ['tables', 'smart', 'with_toc_data']




# Author Directory

authors:

 Jim-Clifford:
   name: Jim Clifford
   bio: |
        Jim Clifford is an assistant professor in the Department of History 
        at the University of Saskatchewan.

 Daniel-Macfarlane:
   name: Daniel Macfarlane
   bio: |
        Daniel Macfarlane is a Visiting Scholar in the School of Canadian
        Studies at Carleton University.

 Josh-MacFadyen:
   name: Josh MacFadyen
   bio: |
        Josh MacFadyen is a Project Coordinator at the Network in Canadian 
        History & Environment.

 William-J.-Turkel:
   name: William J. Turkel
   url: "http://williamjturkel.net"
   twitter: williamjturkel
   github: williamjturkel
   bio: |
        William J. Turkel is an Associate Professor of History at the University of 
        Western Ontario and director of Digital Infrastructure for the Network in Canadian History & 
        Environment (NiCHE).

 Adam-Crymble:
   name: Adam Crymble
   github: acrymble
   email: adam.crymble@gmail.com
   twitter: Adam_Crymble
   url: "http://adamcrymble.org"
   bio: |
        Adam Crymble is a Lecturer of Digital History at the University of 
        Hertfordshire.

 Caleb-McDaniel:
   name: Caleb McDaniel
   bio: |
        Caleb McDaniel is an assistant professor of history at Rice University.

 Ian-Milligan:
   name: Ian Milligan
   bio: |
        Ian Milligan is an assistant professor of history at the University
        of Waterloo.

 Fred-Gibbs:
   name: Fred Gibbs
   email: fwgibbs@gmail.com
   url: "http://fredgibbs.net"
   github: fredgibbs
   twitter: fredgibbs
   bio: |
        Fred Gibbs is an assistant professor of history at the University of
        New Mexico.

 Kellen-Kurschinski:
   name: Kellen Kurschinski
   twitter: Kellen2K
   bio: |
        Kellen Kurschinski is a doctoral candidate in history at McMaster
        University and a Research Officer at the University of Waterloo.

 Seth-Bernstein:
   name: Seth Bernstein
   bio: |
        Seth Bernstein is a postdoctoral fellow at the Higher School of Economics 
        in Moscow.  He defended his doctoral dissertation, "Communist Upbringing 
        under Stalin: The Political Socialization and Militarization of Soviet 
        Youth, 1934-1941" at the University of Toronto in 2013.

 James-Baker:
   name: James Baker
   bio: |
        James Baker is a Curator in the Digital Research team at the British 
        Library and an historian of eighteenth century Britain.

 Amanda-Morton:
   name: Amanda Morton
   bio: |
        Amanda Morton is a DH Fellow at the Center for History and New Media.
