name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
url: http://programminghistorian.org
baseurl: /jekyll
permalink: :title
safe: true
pygments: true
markdown: kramdown
